# src/conda.yaml
channels:
  - conda-forge
dependencies:
  - python=3.8.16
  - pip<=21.3.1
  - pip:
    - mlflow==2.7.1
    - cloudpickle==2.2.1
    - scikit-learn==1.3.0
    - pandas==2.0.3
    - numpy==1.24.3
    - joblib==1.3.2
name: mlflow-env